-- =========================================================
-- Script para crear la tabla MENU_OPCIONES en Oracle 19c
-- Representa las opciones del menú de un restaurante
-- =========================================================

CREATE TABLE MENU_OPCIONES (
    -- ID autoincremental, clave primaria
                               ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,

    -- Nombre del platillo
                               PLATILLO VARCHAR2(100) NOT NULL,

    -- Descripción del platillo
                               DESCRIPCION VARCHAR2(500),

    -- Ruta o nombre del archivo de imagen del platillo
                               IMAGEN VARCHAR2(255),

    -- Precio del platillo con dos decimales
                               PRECIO NUMBER(8, 2) NOT NULL,

    -- Estado del platillo: 1 = Activo, 0 = Inactivo
                               ESTADO NUMBER(1) DEFAULT 1 CHECK (ESTADO IN (0, 1))
);

-- ===============================================
-- Inserciones de ejemplo en la tabla MENU_OPCIONES
-- ===============================================

-- Ejemplo 1
INSERT INTO MENU_OPCIONES (PLATILLO, DESCRIPCION, IMAGEN, PRECIO, ESTADO)
VALUES ('Tacos al Pastor', 'Tacos de cerdo marinado con piña y cebolla', 'tacos.png', 49.50, 1);

-- Ejemplo 2
INSERT INTO MENU_OPCIONES (PLATILLO, DESCRIPCION, IMAGEN, PRECIO, ESTADO)
VALUES ('Enchiladas Verdes', 'Tortillas rellenas de pollo con salsa verde y queso', 'enchiladas.png', 65.00, 1);

-- Ejemplo 3
INSERT INTO MENU_OPCIONES (PLATILLO, DESCRIPCION, IMAGEN, PRECIO, ESTADO)
VALUES ('Agua de Horchata', 'Bebida tradicional de arroz con canela', 'horchata.png', 25.00, 1);
